# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 515cb57c56e855ce94b73fc70145ae36d1bead516a0b3901b583956f8e431078bc9df07df499aca591226ac8e1eabf849c8f8a3c0a46f8f8201076be82479e6f

test:
  secret_key_base: 62d60e08b476e9cba7c2c4124058f7df0983853932b9baee33fe1382ed09524aa93fb74f67677dfc448c86606b2fe60e8ae9ceecbeb6f7f916dfb32893891635

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
